server:
  port: 9090
  servlet:
    context-path: /CEFET

spring:
  application:
    name: atvRodrigo

  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5429/cefet
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Opções: create, create-drop, update, validate, none
    show-sql: true  # Exibe as queries SQL no console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
