server:
  port: 9090
  servlet:
    context-path: /CEFET

spring:
  application:
    name: atvRodrigo

  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5429/cefet
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
    # ddl-auto: update  # Desabilitado para usar o Flyway no gerenciamento do schema
    show-sql: true  # Exibe as queries SQL no console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true  # Habilita o Flyway
    locations: classpath:db/migration  # Caminho onde estão os scripts de migração Flyway
    baseline-on-migrate: true  # Garante que o Flyway considera o estado inicial
